version: "3.8"

services:
  db:
    image: postgres:15
    container_name: mypostgres
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: mypgadmin
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "8080:80"
    restart: unless-stopped

  server:
    build: ./server
    container_name: myserver
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "5000:5000"
    command: ["node", "index.js"]
    restart: unless-stopped

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: myclient
    depends_on:
      - server
    ports:
      - "3000:3000"
    restart: unless-stopped

volumes:
  db_data:
