version: "3.8"

services:
  db:
    image: postgres:15
    container_name: mypostgres_dev
    env_file:
      - .env.dev
    volumes:
      - db_data_dev:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: mypgadmin_dev
    env_file:
      - .env.dev
    depends_on:
      - db
    ports:
      - "8080:80"
    restart: unless-stopped

  server:
    build: ./server
    container_name: myserver_dev
    env_file:
      - .env.dev
    volumes:
      - ./server:/usr/src/app
    depends_on:
      - db
    ports:
      - "5000:5000"
    command: ["npx", "nodemon", "index.js"]
    restart: unless-stopped

volumes:
  db_data_dev:
